// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppTopBar: typeof import('./components/AppTopBar.vue')['default']
    Bottom: typeof import('./components/Bottom.vue')['default']
    Candle: typeof import('./components/Candle.vue')['default']
    Cards: typeof import('./components/Cards.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionSeparator: typeof import('./components/SectionSeparator.vue')['default']
    SmokeLetters: typeof import('./components/SmokeLetters.vue')['default']
  }
}

export {}
